// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKEeLYqo9Ha9iXeF7cjRIoPioH9aozKy4',
    appId: '1:208323944916:web:814b5754a751cf03e93641',
    messagingSenderId: '208323944916',
    projectId: 'credit-app-3f90a',
    authDomain: 'credit-app-3f90a.firebaseapp.com',
    storageBucket: 'credit-app-3f90a.appspot.com',
    measurementId: 'G-721NEDCCXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4UYscM449f8Bp7c-RShZIJ5ta6HYeGCs',
    appId: '1:208323944916:android:c297c070b4d71ce3e93641',
    messagingSenderId: '208323944916',
    projectId: 'credit-app-3f90a',
    storageBucket: 'credit-app-3f90a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIc9K276640FJzNm90zNrrWNEowrdtmD4',
    appId: '1:208323944916:ios:0fbba862a41e247be93641',
    messagingSenderId: '208323944916',
    projectId: 'credit-app-3f90a',
    storageBucket: 'credit-app-3f90a.appspot.com',
    iosBundleId: 'com.example.moderncreditapp',
  );
}
